# Name of the package if any. Package.ModuleName will be the module name 
package_name = "triqs_modest"

# The documentation string of the module. 
documentation = "Python Module for TRIQS Modular Electronic Structure Toolkit"

# Namespace. 
# Only the classes/functions/enums declared in this namespace will be wrapped
namespaces = "triqs triqs::modest  triqs::lattice"

# Match/reject elements according to regex
# If match_names/match_names are both set, filter for all elements 
# Algorithm is (for an element X of fully qualified name Qname)
#    if match_names and not match_names match Qname : skip X
#    if reject_names and reject_names match Qname : skip X
#    else keep X.

match_names = "triqs::modest::|triqs::(root_finder|make_kanamori|make_slater|U_matrix_in_spherical_basis|tb_hamiltonian|fold)|triqs::lattice::(superlattice|bz_int_options)"
reject_names = "triqs::modest::(ibz_symmetry_ops|rotate_local_basis)"

# Only keep elements declared in files matching the pattern
# match_files = "" # String must be a regex

exclude_system_headers = false
wrap_no_arg_methods_as_properties = true
