# Name of the package if any. Package.ModuleName will be the module name
package_name = "triqs"

# The documentation string of the module.
documentation = '''Temporary method of wrapping of necessary objects from the TRIQS library.
'''

# Namespace.
# Only the classes/functions/enums declared in this namespace will be wrapped
namespaces = "triqs triqs::lattice triqs::tb"

# Match/reject elements according to regex
# If match_names/match_names are both set, filter for all elements
# Algorithm is (for an element X of fully qualified name Qname)
#    if match_names and not match_names match Qname : skip X
#    if reject_names and reject_names match Qname : skip X
#    else keep X.

match_names = "triqs::lattice::(find_chemical_potential|gloc|bz_int_options)|triqs::tb::(tb_hamiltonian)"

# Only keep elements declared in files matching the pattern
# match_files = "" # String must be a regex

exclude_system_headers = false
wrap_no_arg_methods_as_properties = true
